### ISSUE TITLE
Blank Screen On Example App

### ISSUE THREAD

**Issue by Moizsohail** [Mobile-Telematics/telematicsSDK-demoapp-react#2]
Steps to reproduce 
```
/root-dir/$ yarn
/root-dir/example$ yarn android && yarn start
```
Emulator Info
![image](https://user-images.githubusercontent.com/32095770/185422537-5386bc07-7255-40f5-83b0-3e0e8f9f51ea.png)

Getting blank screen
![image](https://user-images.githubusercontent.com/32095770/185422252-90e98d2a-ad71-4ddb-b03d-fe6c8c3c98a2.png)

No errors on console 
![image](https://user-images.githubusercontent.com/32095770/185422375-d2d80886-1848-4506-ab2b-ce2deca7018b.png)

**Comment by telematicsgig** [comment]
Hey, we just deployed the demo app, and it works with no issues. Please take a look at the attachment. 
make sure you execute yarn first, then yarn android
![Снимок экрана 2022-08-19 в 09 24 29](https://user-images.githubusercontent.com/85515799/185745612-aa9470a6-a514-451a-9561-47622c5ca65b.png)
